# Setup
title: D-Seeker
description: 某在校本科生，欢迎来到我的博客，用于记录学习，大家一起学习进步！
url: https://D-Seeker.github.io
avatar: /head.jpg
paginate: 5
permalink: pretty
cover_image: /bg.png

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
# twitter:
#   username: D-Seeker
#   card: summary
# logo: logo.png
# social:
#   name: D-Seeker
#   links:
#     - https://github.com/D-Seeker
# google_site_verification: xxxxx
# lang: en

# sass:
#   sass_dir: _sass
#   style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: D-Seeker
  url: https://github.com/D-Seeker/
  email: DSeekerLu@outlook.com
